# Generated by Django 5.2.8 on 2026-03-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_couponoffer_economy_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='couponoffer',
            new_name='promo_coupo_is_acti_75c4b6_idx',
            old_name='promo_coupo_is_acti_34e10a_idx',
        ),
        migrations.RenameIndex(
            model_name='couponoffer',
            new_name='promo_coupo_is_acti_d7c784_idx',
            old_name='promo_coupo_is_acti_6cb3b5_idx',
        ),
    ]
