# Generated by Django 5.2.8 on 2026-05-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0007_couponoffer_cafe_required_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coupon_offers/', verbose_name='Фон купона'),
        ),
    ]
