# Generated by Django 5.2.8 on 2026-06-02 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0008_cafe_coupon_bg_menuitem_image_focus'),
        ('promo', '0010_reprice_coupons_by_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponoffer',
            name='cost_points10',
            field=models.PositiveIntegerField(default=500, verbose_name='Цена (баллы x10)'),
        ),
        migrations.AlterField(
            model_name='couponoffer',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_offers', to='cafes.menuitem', verbose_name='Блюдо меню'),
        ),
    ]
