# Generated by Django 5.2.8 on 2026-03-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_cafe_latitude_cafe_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'ordering': ['name'], 'verbose_name': 'Кафе', 'verbose_name_plural': 'Кафе'},
        ),
        migrations.AlterModelOptions(
            name='cafestaff',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сотрудник кафе', 'verbose_name_plural': 'Сотрудники кафе'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['id'], 'verbose_name': 'Категория меню', 'verbose_name_plural': 'Категории меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['id'], 'verbose_name': 'Позиция меню', 'verbose_name_plural': 'Позиции меню'},
        ),
    ]
