# Generated by Django 5.2.8 on 2026-05-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0007_city_cafe_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='coupon_bg',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/coupon_bg/', verbose_name='Фон купонов кафе'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_focus',
            field=models.CharField(choices=[('center', 'Центр'), ('top', 'Сверху'), ('bottom', 'Снизу'), ('left', 'Слева'), ('right', 'Справа')], default='center', help_text='Где находится блюдо на фото', max_length=20, verbose_name='Фокус фото'),
        ),
    ]
