# Generated by Django 5.2.8 on 2026-03-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_order', '0003_order_points_accrued'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duplicate_signature',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Сигнатура дубля'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_duplicate',
            field=models.BooleanField(default=False, verbose_name='Дубликат чека'),
        ),
    ]
