# Generated by Django 5.2.8 on 2026-05-21 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_feedevent_rarity'),
        ('user_profile', '0016_promocode_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedevent',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_events', to='user_profile.promocode'),
        ),
    ]
