# Generated by Django 5.2.8 on 2026-02-13 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0005_promocode_rename_user_remove_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={
                'ordering': ['-acquired_at'],
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
