# Generated by Django 5.2.8 on 2026-03-16 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_rename_promo_coupo_is_acti_34e10a_idx_promo_coupo_is_acti_75c4b6_idx_and_more'),
        ('user_profile', '0012_promocode_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='source_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_promocodes', to='promo.couponoffer', verbose_name='Шаблон награды'),
        ),
    ]
