# Generated by Django 5.2.8 on 2026-05-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0007_city_cafe_city'),
        ('user_profile', '0013_alter_promocode_source_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='cafes.city', verbose_name='Город'),
        ),
    ]
