# Generated by Django 5.2.8 on 2026-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_order_xp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_post_xp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
