# Generated by Django 5.2.8 on 2026-05-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_profile_last_order_xp_date_profile_last_post_xp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='activation_code',
            field=models.CharField(blank=True, db_index=True, max_length=4, verbose_name='Код активации (4 символа)'),
        ),
    ]
